---
- hosts: node-01
  become: yes
  tasks:
    - name: create ext4 files system on logical volume
      filesystem:
        fstype: ext4
        dev: /dev/mapper/vg_ansible-lv_ansible
    - name: mount filesystem
      mount:
        path: /mnt/test_mount
        src: /dev/mapper/vg_ansible-lv_ansible
        fstype: ext4
        state: mounted
        backup: yes
